$.lang = {};

$.lang.ko = {
    0: '언어',
    1: '대화목록',
	2: '대화상대',
	3: '알림목록',
    4: '더보기',
    5: '조직도 보기',
    6: '사용자 찾기',
    7: '그룹웨어 홈',
    8: '옵션설정',
    9: '계정변경',
    10: '업데이트',
    11: '나의 프로필',
    12: '조직도 보기',
    13: '사용자 찾기',
    14: '옵션설정',
    15: '사용자정보',
    16: '대화방 만들기',
    17: '대화하기',
    18: '알림 지우기',
    19: '로그아웃',
    20: '종료',
    21: '이름',
    22: '소속',
    23: '직급',
    24: '부서',
    25: '연락처',
    26: '휴대폰',
    27: '이메일',
    28: '담당업무',
    29: '뒤로',
    30: '완료',
    31: '찾는 분의 이름을 입력하세요.',
    32: '찾기',
    33: '상태메시지를 입력하세요.',
    34: '업데이트',
    35: '등록된 상태메시지가 없습니다.',
    36: '대화방명 변경',
    37: '줄바꿈: Shift+Enter / Ctrl+Enter',
    38: '<p style="margin:5px 10px">보내기<br style="margin:0">(Enter)</p>',
    39: '프로그램 재실행 후 다시 시도해주세요.',
    40: '권한코드를 부여받지 못했습니다. 관리자에게 문의하세요.',
    41: '바로가기 만들기',
    42: '대화방명 변경',
    43: '대화상대 초대',
    44: '대화방 참여자',
    45: '나가기',
    46: '삭제',
    47: '오늘',
    48: '실행',
    49: '닫기',
    50: '회사명',
    51: '사진',
    52: '원형 테두리',
    53: '알림',
    54: '수신음',
    55: '알림창',
    56: '로그인',
    57: '자동 로그인',
    58: '위 계정으로 다른 디바이스에서 접속했습니다.',
    59: '회사명을 입력해주세요.',
    60: '그룹웨어로 로그인하시겠습니까?',
    61: '님은 대화에 참여중입니다.',
    62: '현재버전',
    63: '이미지 파일이 아닙니다.',
    64: '미등록 대화상대',
    65: '옵션을 적용하려면 트레이메뉴에서 프로그램 종료 후 재실행해야 합니다.',
    66: '계정변경을 위해서 모든 데이터가 삭제된 후 프로그램이 종료됩니다. 계속하시겠습니까?',
    67: '대화방에서 나가시면 대화내용이 모두 지워집니다. 계속하시겠습니까?',
    68: '사진 및 파일은 1개 씩 전송이 가능합니다.',
    69: '님을 초대하셨습니다.',
    70: '퇴장하셨습니다.',
    71: '[사진전송]',
    72: '[파일전송]',
    73: '[초대알림]',
    74: '[퇴장알림]',
    75: '메신저 로그인',
    76: '그룹웨어 로그인',
    77: '이메일주소',
    78: '비밀번호',
    79: '모바일 주소록',
};

$.lang.en = {
    0: 'Language',
    1: 'Chat',
	2: 'Buddy',
	3: 'Notification',
	4: 'More',
    5: 'Organization',
    6: 'Find User',
    7: 'Groupware Home',
    8: 'Options',
    9: 'Account Change',
    10: 'Update',
    11: 'My Profile',
    12: 'Company',
    13: 'Find User',
    14: 'Options Settings',
    15: 'User Information',
    16: 'Make Chat',
    17: 'Chatting',
    18: 'Clear Notifications',
    19: 'Logout',
    20: 'Exit',
    21: 'Name',
    22: 'Company',
    23: 'Position',
    24: 'Department',
    25: 'Telephone',
    26: 'Cell Phone',
    27: "Email",
    28: 'Responsibilities',
    29: 'Back',
    30: 'Done',
    31: 'Please enter the name.',
    32: 'Find',
    33: 'Please enter a status message.',
    34: 'Update',
    35: 'There are no status messages registered.',
    36: 'Change Room Name',
    37: 'Line break: Shift+Enter / Ctrl+Enter',
    38: '<p style="margin:5px 10px">Send<br style="margin:0">(Enter)</p>',
    39: 'Please re-run the program and try again.',
    40: 'Failed to get permission code. Please contact your administrator.',
    41: 'Create Shortcut',
    42: 'Change chat name',
    43: 'Invite',
    44: 'Participants',
    45: 'Exit',
    46: 'Delete',
    47: 'Today',
    48: 'Show',
    49: 'Close',
    50: 'Company name',
    51: 'Pictures',
    52: 'Circular border',
    53: 'Notifications',
    54: 'Sound',
    55: 'Popup',
    56: 'Login',
    57: 'Auto Login',
    58: 'You have connected to the above account from another device.',
    59: 'Please enter your company name.',
    60: 'Do you want to log in as groupware account?',
    61: ' is in a conversation.',
    62: 'Current Version',
    63: 'Not a image file',
    64: 'Unregistered contacts',
    65: 'To apply an option, you must re-launch it from the Tray menu after exiting the program.',
    66: 'The program will be terminated after all data has been deleted in order to change the account. Do you want to continue?',
    67: 'When you leave the chat room, all your conversations are cleared. Do you want to continue?',
    68: 'Pictures and files can be transferred one by one.',
    69: ' is invited.',
    70: ' is out.',
    71: '[Picture]',
    72: '[File]',
    73: '[Invitation]',
    74: '[Exit]',
    75: 'Messenger Login',
    76: 'Groupware Login',
    77: 'Email address',
    78: 'Password',
    79: 'Mobile contacts',
};
